name: CI/CD pipeline
on:
    push:
        branches:
        - main

jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Set up JDK 21
          uses: actions/setup-java@v4
          with:
            java-version: '21'
            distribution: 'temurin'
        - name: Build with Maven
          run: mvn clean package -DskipTests
        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        - name: Build and push Docker image
          run: |
            docker build -t ${{ secrets.DOCKER_USERNAME }}/user-service:latest .
            docker push ${{ secrets.DOCKER_USERNAME }}/user-service:latest